name: municipal 5 horas
on:
  schedule:
    - cron: '* 5 * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run notebooks
        id: run_notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --ExecutePreprocessor.kernel_name=python3 --execute covid_municipal.ipynb
      - name: git status
        id: git-status
        run: |
          git config --global user.email "covid-bot@example.com"
          git config --global user.name "covid-bot"
          echo ::set-output name=result::$(git status ./ | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DATE: ${{ steps.update-script.outputs.result }}
        run: |
          git add -A
          git commit -m "[ci] $DATE"
          git push -q "https://$GH_TOKEN@github.com/dquintani/covid.git" main
